development:
  adapter: postgresql 
  encoding: unicode
  database: highlighter_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql 
  encoding: unicode
  database: highlighter_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql 
  encoding: unicode
  database: highlighter_production
  pool: 5
  username:
  password:
